dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - yarn

script:
  - yarn test s-ng-utils --code-coverage --watch=false --progress=false --browsers=ChromeHeadlessCI
  - yarn build s-ng-utils --prod
  - yarn e2e --protractor-config=./e2e/protractor-ci.conf.js

after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js

notifications:
  email: false
