dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - yarn

script:
  - yarn test s-ng-utils --code-coverage --watch=false --progress=false --browsers=ChromeHeadlessCI

  - mkdir ~/.dts
  - yarn dtslint

  - yarn build s-ng-utils
  - yarn e2e --protractor-config=./e2e/protractor-ci.conf.js

after_success:
  - cat coverage/s-ng-utils/lcov.info | node_modules/coveralls/bin/coveralls.js

notifications:
  email: false
